travis:
  secure:
    BINSTAR_TOKEN: wj5yXQc/OO5IomSDsjgjaYtqI+WvL3+OobKOc1JlMt3H07I3lT6SSSb/t1gGXRjVrhv49jxpUkZmy3JSsYaXRRtsxi+Xh3ij8C/vS96lbAsrQ0xFWLLn48hnt9Tpi1zkAnzmCPkAvKVdlGw8Ry4IJaOCx+4J3togQTngXZLZjNm5zCMHjVRFwvKRlJRqPe+H4yUrqJthPqir2boZ+qRHbDPC4mp6ufl8tqgbIx5TQer3ZPNtxr0/vk3uxzTT3m3lwPzkd/MuXhJteK8RV/eSI/qQaql2g4DVQOanP3agPFBHVG7rVlYlmHN4Iz8dJgbZ4Y1Tos0fYMv22kMVUV7ZqI3sIZTihG181NwEBEsBJFewEKwM7ezGxZYAasdMVLCrdpNQXGSWusXjHhQkT5M8Zvz+ktSc4xCl/2TpI8/rWVsuoNya4lwqrCXE8Qm6TsI51FFN5HThtL8zXmLNRDNKG/6tWsyP6VU4DISPKvlXA6Am3Nm6egx9dtezwXTuytpbdm0EKAUtd2iDf8CL5zcALP/ujMG59I7xPCgX1ZkkilSo4koDCapOXUsDzOsnUyoZPVQtI3xTkoDj6XdYyw++qNvndvOH3/9PVWTliD+ayhTA4OhrzwlIaqlpFUlecyJik1uoCl/Fwa9JASlGxrisgpBKWvlW0xHJ2HxsZT+bKVA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
